### ISSUE TITLE
Return key doesn't start new line, but rather moves cursor to beginning of input

### ISSUE THREAD

**Issue by Shaolin69** [Backendless/ui-builder-library#442]
Return key works on the 1st line of the editor... but every line after that: return key moves cursor to top of the editor. This makes the editor essentially not useable.

**Comment by stanislav-grin** [comment]
Hello @Shaolin69,
sorry for not informing you about the update. I checked and see that the ticket was created, the fix was made and the component was updated in the marketplace. Could you please check again (need to reinstall the component again) and let us know if everything is fine now? By the way, in the near future we plan to make automatic updating of components, so in the future to update a component you will only need to click one button.

**Comment by snaqqqystas** [comment]
@Shaolin69, this bug has been fixed in last Rich Editor version (1.4.0), you can install it from the marketplace.
Also, a new (versions) feature, described by Stanislav Green, already available on the Backendless.
